// <auto-generated />
using System;
using BaithuchanhWeb2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaithuchanhWeb2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250916080949_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaithuchanhWeb2.Models.Domain.Authors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Nguyễn Nhật Ánh"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Tô Hoài"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Nam Cao"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Ngô Tất Tố"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Vũ Trọng Phụng"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Nguyễn Du"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Xuân Quỳnh"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Hồ Chí Minh"
                        });
                });

            modelBuilder.Entity("BaithuchanhWeb2.Models.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverUrl = "https://example.com/kinh-van-hoa.jpg",
                            DateAdded = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRead = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Một cuốn sách hay về tuổi thơ và những kỷ niệm đẹp",
                            Genre = "Văn học thiếu nhi",
                            IsRead = true,
                            PublisherId = 1,
                            Rate = 5,
                            Title = "Kính vạn hoa"
                        },
                        new
                        {
                            Id = 2,
                            CoverUrl = "https://example.com/de-men.jpg",
                            DateAdded = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRead = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cuốn sách kinh điển về cuộc phiêu lưu của chú dế Mèn",
                            Genre = "Văn học thiếu nhi",
                            IsRead = true,
                            PublisherId = 2,
                            Rate = 5,
                            Title = "Dế Mèn phiêu lưu ký"
                        },
                        new
                        {
                            Id = 3,
                            CoverUrl = "https://example.com/chi-pheo.jpg",
                            DateAdded = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRead = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tác phẩm nổi tiếng của Nam Cao về số phận con người",
                            Genre = "Văn học hiện đại",
                            IsRead = true,
                            PublisherId = 3,
                            Rate = 4,
                            Title = "Chí Phèo"
                        },
                        new
                        {
                            Id = 4,
                            CoverUrl = "https://example.com/tat-den.jpg",
                            DateAdded = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tiểu thuyết đầu tay của Ngô Tất Tố về đời sống nông thôn",
                            Genre = "Văn học hiện đại",
                            IsRead = false,
                            PublisherId = 3,
                            Title = "Tắt đèn"
                        },
                        new
                        {
                            Id = 5,
                            CoverUrl = "https://example.com/so-do.jpg",
                            DateAdded = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRead = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tác phẩm châm biếm xã hội của Vũ Trọng Phụng",
                            Genre = "Văn học hiện đại",
                            IsRead = true,
                            PublisherId = 4,
                            Rate = 4,
                            Title = "Số đỏ"
                        },
                        new
                        {
                            Id = 6,
                            CoverUrl = "https://example.com/truyen-kieu.jpg",
                            DateAdded = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kiệt tác văn học cổ điển Việt Nam",
                            Genre = "Văn học cổ điển",
                            IsRead = false,
                            PublisherId = 5,
                            Title = "Truyện Kiều"
                        },
                        new
                        {
                            Id = 7,
                            CoverUrl = "https://example.com/song.jpg",
                            DateAdded = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRead = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tập thơ nổi tiếng của nhà thơ Xuân Quỳnh",
                            Genre = "Thơ",
                            IsRead = true,
                            PublisherId = 5,
                            Rate = 5,
                            Title = "Sóng"
                        });
                });

            modelBuilder.Entity("BaithuchanhWeb2.Models.Domain.Book_Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookId");

                    b.ToTable("Books_Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            BookId = 1
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            BookId = 2
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            BookId = 3
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            BookId = 4
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            BookId = 5
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            BookId = 6
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            BookId = 7
                        });
                });

            modelBuilder.Entity("BaithuchanhWeb2.Models.Domain.Publishers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NXB Kim Đồng"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NXB Trẻ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NXB Văn học"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NXB Giáo dục Việt Nam"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NXB Hội Nhà văn"
                        });
                });

            modelBuilder.Entity("BaithuchanhWeb2.Models.Domain.Book", b =>
                {
                    b.HasOne("BaithuchanhWeb2.Models.Domain.Publishers", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BaithuchanhWeb2.Models.Domain.Book_Author", b =>
                {
                    b.HasOne("BaithuchanhWeb2.Models.Domain.Authors", "Author")
                        .WithMany("Book_Authors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaithuchanhWeb2.Models.Domain.Book", "Book")
                        .WithMany("Book_Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BaithuchanhWeb2.Models.Domain.Authors", b =>
                {
                    b.Navigation("Book_Authors");
                });

            modelBuilder.Entity("BaithuchanhWeb2.Models.Domain.Book", b =>
                {
                    b.Navigation("Book_Authors");
                });

            modelBuilder.Entity("BaithuchanhWeb2.Models.Domain.Publishers", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
